= Pod, ReplicaSet, Deployment


* *Terminal#1에서 수행*
먼저 작업할 네임스페이스를 만듭니다.:

[#create-namespace]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc new-project myspace-%userid%
----

[#create-namespace]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project myspace-%userid% 
----


== Pod

NOTE: pod 생성 명령어 수행 전에 아래 명령어를 수행하여, Pod 생성 단계에서 수명주기를 살펴보세요.:

[#watch-pod]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
watch oc get pods
----

[.console-output]
[source,bash]
----
NAME           READY   STATUS              RESTARTS   AGE
quarkus-demo   0/1     ContainerCreating   0          10s
----


[.console-output]
[source,bash]
----
NAME           READY   STATUS    RESTARTS   AGE
quarkus-demo   1/1     Running   0          18s
----

NOTE: Pod 생성시, `ContainerCreating` 상태에서 `Running` 상태로 변경되는 것을 확인할 수 있습니다.


* *Terminal#2에서 수행*


[#create-namespace]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project myspace-%userid% 
----

https://kubernetes.io/docs/concepts/configuration/overview/#naked-pods-vs-replicasets-deployments-and-jobs[naked pod]를 생성합니다.:

[#create-pod]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: quarkus-demo
spec:
  containers:
  - name: quarkus-demo
    image: quay.io/rhdevelopers/quarkus-demo:v1
EOF
----



Pod에서 애플리케이션 확인:

[#verify-pod]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc exec -it quarkus-demo -- /bin/sh
----

다음 명령을 실행하세요.
컨테이너 인스턴스 내부에 있으므로 호스트 이름은 'localhost'입니다.

[#curl-inside-pod]
[.console-input]
[source,bash]
----
curl localhost:8080
----

[.console-output]
[source,bash]
----
Supersonic Subatomic Java with Quarkus quarkus-demo:1
----

pod에서 빠져 나오세요.

[#curl-inside-pod]
[.console-input]
[source,bash]
----
exit
----

이제 Pod를 삭제해 보겠습니다:

[#delete-naked-pod]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete pod quarkus-demo
----

* *Terminal#2에서 확인*

[#watch-all-naked-pod]
[.console-input]
[source,bash]
----
watch oc get pods
----

[.console-output]
[source,bash]
----
NAME           READY   STATUS        RESTARTS   AGE
quarkus-demo   0/1     Terminating   0          9m35s

No resources found in myspace namespace.
----

NOTE: `Naked pod` 는 클러스터에서 영원히 삭제됩니다. 이처럼 직접 pod만 생성하게 되는 Naked Pods는 노드 장애 발생 시 재예약되지 않습니다. +
원하는 수의 Pod가 항상 사용 가능하도록 ReplicaSet을 생성하고 Pod를 대체하기 위한 전략(예: RollingUpdate )을 지정하는 Deployment는 일부 명시적 시나리오를 제외하고는 Pod를 직접 생성하는 것보다 바람직합니다 

NOTE: `watch`명령어는 [ctrl+c]를 입력하여 빠져 나옵니다.

== ReplicaSet

ReplicaSet 생성:

* *Terminal#1에서 수행*

[#create-replicaset]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: rs-quarkus-demo
spec:
    replicas: 3
    selector:
       matchLabels:
          app: quarkus-demo
    template:
       metadata:
          labels:
             app: quarkus-demo
             env: dev
       spec:
          containers:
          - name: quarkus-demo
            image: quay.io/rhdevelopers/quarkus-demo:v1
EOF
----

라벨이 있는 Pod 목록을 가져옵니다.:

[#replicaset-show-labels]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
watch oc get pods --show-labels
----

[.console-output]
[source,bash]
----
NAME                    READY   STATUS    RESTARTS   AGE   LABELS
rs-quarkus-demo-jd6jk   1/1     Running   0          58s   app=quarkus-demo,env=dev
rs-quarkus-demo-mlnng   1/1     Running   0          58s   app=quarkus-demo,env=dev
rs-quarkus-demo-t26gt   1/1     Running   0          58s   app=quarkus-demo,env=dev
----


* *Terminal#2에서 수행*

[#get-rs]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get rs
----

[.console-output]
[source,bash]
----
NAME              DESIRED   CURRENT   READY   AGE
rs-quarkus-demo   3         3         3       79s
----

Replicasets 정보를 확인하세요.:

[#describe-rs-quarkus-demo]
[.console-input]
[source,bash]
----
oc describe rs rs-quarkus-demo
----

[.console-output]
[source,bash]
----
Name:         rs-quarkus-demo
Namespace:    myspace
Selector:     app=quarkus-demo
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{},"name":"rs-quarkus-demo","namespace":"myspace"},"spec":{"replicas...
Replicas:     3 current / 3 desired
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=quarkus-demo
           env=dev
  Containers:
   quarkus-demo:
    Image:        quay.io/rhdevelopers/quarkus-demo:v1
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  89s   replicaset-controller  Created pod: rs-quarkus-demo-jd6jk
  Normal  SuccessfulCreate  89s   replicaset-controller  Created pod: rs-quarkus-demo-t26gt
  Normal  SuccessfulCreate  89s   replicaset-controller  Created pod: rs-quarkus-demo-mlnng
----

NOTE: Pod는 ReplicaSet에 의해 "소유"됩니다.


이제 Pod를 확인하면서 Pod를 삭제하세요.:


[#replicaset-show-labels]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get pods 
----

[.console-output]
[source,bash]
----
NAME                    READY   STATUS    RESTARTS   AGE  
rs-quarkus-demo-jd6jk   1/1     Running   0          58s   
rs-quarkus-demo-mlnng   1/1     Running   0          58s   
rs-quarkus-demo-t26gt   1/1     Running   0          58s   
----


[#delete-pod-rs]
[.console-input]
[source,bash]
----
oc delete pod rs-quarkus-demo-mlnng
----

IMPORTANT: 명령어의 pod name(rs-quarkus-demo-mlnng 부분)은 실제 조회된 pod의 값으로 변경해야 합니다.

그러면 이를 대체할 새로운 Pod가 생겨나게 됩니다.:

[.console-output]
[source,bash]
----
NAME                    READY   STATUS              RESTARTS   AGE    LABELS
rs-quarkus-demo-2txwk   0/1     ContainerCreating   0          2s     app=quarkus-demo,env=dev
rs-quarkus-demo-jd6jk   1/1     Running             0          109s   app=quarkus-demo,env=dev
rs-quarkus-demo-t26gt   1/1     Running             0          109s   app=quarkus-demo,env=dev
----

연결된 모든 Pod를 제거하려면 ReplicaSet를 삭제하세요.:

[#delete-rs]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete rs rs-quarkus-demo
----



== Deployment

Deployment를 배포합니다. (Replicaset 3을 포함하고 있습니다)

* *Terminal#2에서 수행*

[#create-deployment]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quarkus-demo
  template:
    metadata:
      labels:
        app: quarkus-demo
        env: dev
    spec:
      containers:
      - name: quarkus-demo
        image: quay.io/rhdevelopers/quarkus-demo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
EOF
----

라벨을 포함한 pod 리스트를 조회합니다.

[#pod-show-labels-dep]
[.console-input]
[source,bash]
----
oc get pods --show-labels
----

[.console-output]
[source,bash]
----
NAME                                       READY   STATUS    RESTARTS   AGE   LABELS
quarkus-demo-deployment-5979886fb7-c888m   1/1     Running   0          17s   app=quarkus-demo,env=dev,pod-template-hash=5979886fb7
quarkus-demo-deployment-5979886fb7-gdtnz   1/1     Running   0          17s   app=quarkus-demo,env=dev,pod-template-hash=5979886fb7
quarkus-demo-deployment-5979886fb7-grf59   1/1     Running   0          17s   app=quarkus-demo,env=dev,pod-template-hash=5979886f
----

NOTE: Deployment에 Replicaset :3 값이 포함되어 있기 때문에 3개의 Pod가 실행됨을 확인할 수 있습니다. 



다음 섹션에서는 `Service`의 개념을 배우게 됩니다.
이는 Kubernetes 생태계에서 중요한 요소입니다.
