= Service

이제 우리는 Kubernetes에서 서비스(Service)를 생성하고 트래픽을 관리하는 방법을 살펴볼 것입니다.
Service 오브젝트를 사용하여 RHOCP에서 내부 Pod 간 네트워크 통신을 안정적으로 구성할 수 있습니다. 


== Pod 및 서비스의 IP 주소

Kubernetes는 자동으로 모든 Pod에 IP 주소를 할당합니다. 
그러나 Pod는 임시 객체이므로 Pod IP 주소로 연결하는 것은 불안정합니다. 

클러스터의 노드 전반에서 Pod가 끊임없이 생성되고 제거되기 때문인데, 예를 들어 애플리케이션의 새 버전을 배포하면 Kubernetes는 기존 Pod를 제거한 다음 새 Pod를 배포합니다.

Kubernetes Pod 내 컨테이너는 서로의 동적 IP 주소에 직접 연결되지 않아야 합니다. 

대신 Kubernetes는 Service 리소스에 안정적인 IP 주소를 할당합니다. 
그런 다음 Service는 특정 label을 가진 Pod들에 대해 가상 네트워크 로드밸런서 역할을 합니다.

Pod가 다른 노드에서 다시 시작, 복제 또는 재조정되어도 Service의 엔드포인트가 자동으로 업데이트되면서 Pod에 대한 Service의 연결이 유지됩니다.
끊임없이 생성/제거 되면서 계속 달라지는 Pod IP 주소와 달리 서비스의 IP 주소는 변경되지 않기 때문에, 애플리케이션에 대한 확장성과 내결함성을 제공할 수 있습니다. 


NOTE: 이 섹션의 실습은 이전 섹션의 deploymets 생성 실습에서 이어집니다.

이전 실습에서 사용하고 있던 프로젝트를 지정합니다.

[#create-namespace]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project myspace-%userid% 
----


Deployments가 있는지 확인하세요.

[#have-deployment-service]
[.console-input]
[source,bash]
----
oc get deployments
----

[.console-output]
[source,bash]
----
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
quarkus-demo-deployment   3/3     3            3           8m33s
----

Replicasets가 있는지 확인하세요

[#have-rs-service]
[.console-input]
[source,bash]
----
oc get rs
----

[.console-output]
[source,bash]
----
NAME                                 DESIRED   CURRENT   READY   AGE
quarkus-demo-deployment-5979886fb7   3         3         3       8m56s
----

Pod가 있는지 확인하세요.

[#have-pods-service]
[.console-input]
[source,bash]
----
oc get pods
----

[.console-output]
[source,bash]
----
NAME                                       READY   STATUS    RESTARTS   AGE
quarkus-demo-deployment-5979886fb7-c888m   1/1     Running   0          9m17s
quarkus-demo-deployment-5979886fb7-gdtnz   1/1     Running   0          9m17s
quarkus-demo-deployment-5979886fb7-grf59   1/1     Running   0          9m17s
----

서비스를 생성합니다.
[#create-service]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Service
metadata:
  name: the-service
spec:
  selector:
    app: quarkus-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
EOF
----

위의 Service에 대한 spec을 한번 살펴봅니다.
Service는 위 텍스트와 같이 셀렉터(Selector)를 설정하여 특정한 레이블(Label)을 기반으로 파드를 자동으로 탐색하도록 되어있습니다.

:section-k8s: services
아래 명령어를 통해 서비스의 클러스터 IP와 PORT를 가져옵니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(oc get service the-service -o jsonpath="{.spec.clusterIP}")
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PORT=$(oc get service the-service -o jsonpath="{.spec.ports[*].port}")
----


Curl the Service:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT
----


결과값:

[.console-output]
[source,bash]
----
Supersonic Subatomic Java with Quarkus quarkus-demo-deployment-5979886fb7-grf59:1
----



== 외부 연결을 위한 인그레스 오브젝트 사용

Kubernetes의 인그레스(Ingress)는 클러스터의 외부 네트워크에 애플리케이션을 노출하기 위한 리소스로, HTTP, HTTPS, SNI(서버 이름 확인)및 TLS(SNI 사용) 트래픽 유형만 허용할 수 있습니다. 

여러 개의 애플리케이션을 운영할 때, 외부에서 들어오는 트래픽을 각각의 도메인 또는 경로(Path)별로 분배할 수 있습니다.

표준 Kubernetes 인그레스 리소스는 일반적으로 최소 기능을 제공합니다. 
TLS 종료, 경로 리디렉션, 고정 세션 등 애플리케이션이 사용하는 많은 일반 기능은 인그레스 컨트롤러에 따라 다릅니다. 

=== Ingress

[#create-ingress]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  namespace: myspace-%userid%
spec:
  rules:
    - host: stuff-myspace-%userid%.%subdomain%
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: the-service
                port:
                  number: 80
EOF
----

Ingress에 설정된 host name을 통해 curl 요청을 합니다.

[#curl-services-ingress]
[.console-input]
[source, bash]
----
curl stuff-myspace-%userid%.%subdomain%
----



[.console-output]
[source,bash]
----
Supersonic Subatomic Java with Quarkus quarkus-demo-deployment-5979886fb7-gdtnz:2
----

NOTE: 이전 방식(서비스의 Cluster IP 및 PORT)과는 다르게 Ingress의 Host(외부 노출)를 통해 curl이 요청이 정상적으로 수행됨을 확인할 수 있습니다.


== 외부 연결을 위한 경로(Route) 사용
RHOCP는 클러스터의 외부 네트워크에 애플리케이션을 노출하기 위한 리소스로 경로(Route)를 제공합니다. 

경로(Route)는 Kubernetes 인그레스 오브젝트보다 더 많은 기능을 제공합니다. 
경로(Route)는 TLS 재암호화, TLS 패스스루, 파랑-녹색 배포를 위한 트래픽 분할 등 표준 인터페이스를 통해 Kubernetes 인그레스 컨트롤러에서는 지원되지 않을 수도 있는 고급 기능을 제공합니다.


=== OpenShift Route

이름 충돌을 방지하려면 이전 단계에서 수동으로 생성한 Ingress를 삭제하세요. OpenShift Route는 기본 Ingress의 ha-proxy를 활용합니다.

[#delete-ingress]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete ingress example
----

[#expose-service]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc expose service the-service
----

NOTE: `oc expose` 명령어는 service를 routes를 통해 외부로 노출시킵니다.


[#expose-service]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get routes
----


[.console-output]
[source,bash]
----
NAME          HOST/PORT                                     PATH   SERVICES      PORT   TERMINATION   WILDCARD
the-service   the-service-myspace-%userid%.%subdomain%          the-service   8080                 None
----

그런 다음 서비스에 요청하십시오.:

[#curl-services-route]
[.console-input]
[source, bash]
----
curl the-service-myspace-%userid%.%subdomain%
----


[.console-output]
[source,bash]
----
Supersonic Subatomic Java with Quarkus quarkus-demo-deployment-5979886fb7-gdtnz:3
----



== Clean Up

[#clean-up]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete service the-service
----

[#clean-up]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete deployment quarkus-demo-deployment
----

지금까지 service를 통한 클러스터 내부에서의 pod 노출과 Route/Ingress를 통한 외부로의 Service 노출을 확인하였습니다.
