= Logs

Kubernetes에서 실행 중인 애플리케이션의 로그를 조회하고, 문제를 진단하는 방법을 알아보겠습니다.

OpenShift Logging은 클러스터의 모든 Pod 및 노드에서 로그 메시지를 수집하고 집계합니다. 사용자와 관리자는 OpenShift 웹 콘솔 또는 CLI를 사용하여 로그 항목을 검색하고 참조할 수 있습니다.


== 사전 구성 

애플리케이션(배포)이 실행 중인지 확인하세요.:


[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc new-project log-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
namespace/log-%userid% created
----

NOTE: `oc new-project  log-%userid%` : log-%userid%라는 새 프로젝트(네임스페이스)를 생성합니다.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project log-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "log-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project log-%userid%` : 현재 활성화된 컨텍스트의 기본 프로젝트를 log-%userid%로 변경합니다.

== 앱 배포

[#create-deployment]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        env: dev
    spec:
      containers:
      - name: myapp
        image: quay.io/rhdevelopers/myboot:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
EOF
----

3개의 복제본(애플리케이션의 3개 Pod/인스턴스)을 실행하고 있는지 확인하세요.:

[#logs-get-replicas]
[.console-input]
[source, bash]
----
oc get deployment my-deployment -o json | jq '.status.replicas'
----

[.console-output]
[source,bash]
----
3
----

그렇지 않은 경우 최대 3개까지 확장하세요.:

[#logs-scale-replicas]
[.console-input]
[source, bash]
----
oc scale --replicas=3 deployment/my-deployment
----

3개의 pod가 배포되어 동작중인지 확인합니다.

[#logs-scale-replicas]
[.console-input]
[source, bash]
----
oc get pod
----


[.console-output]
[source,bash]
----
NAME                             READY   STATUS    RESTARTS   AGE
my-deployment-5dc67997c7-5bq4n   1/1     Running   0          34s
my-deployment-5dc67997c7-m7z9f   1/1     Running   0          34s
my-deployment-5dc67997c7-s4jc6   1/1     Running   0          34s
----

하나의 pod에서 발생 중인 로그를 확인합니다.

[#logs-log-deployment]
[.console-input]
[source, bash]
----
oc logs <POD이름>
----

[#logs-log-deployment]
[.console-input]
[source, bash]
----
(예시) oc logs my-deployment-5dc67997c7-m7z9f
----

IMPORTANT: pod 이름(my-deployment-5dc67997c7-m7z9f)은 `oc get pod`에서 확인된 값으로 변경하여 입력하세요.


[.console-output]
[source]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.3.RELEASE)

----

NOTE: `-f` 매개변수를 사용하면 로그를 실시간으로 출력할 수 있습니다.

[#logs-log-deployment-follow]
[.console-input]
[source, bash]
----
oc logs <POD이름> -f
----

아래는  **다른 터미널(Terminal#2)**에서 실행하세요.:

* *Terminal#2에서 수행*

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project log-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "log-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project log-%userid%` : 현재 활성화된 컨텍스트의 기본 프로젝트를 log-%userid%로 변경합니다.


[.console-input]
[source,bash]
----
oc exec -it <POD이름> -- /bin/bash
----

IMPORTANT: pod 이름은 터미널1에서 로그를 보고 있는 POD의 이름으로 변경하여 입력하세요.

[.console-input]
[source,bash]
----
curl localhost:8080
----

터미널1의 로그에 아래와 같은 내용이 출력되는 것을 보실 수 있습니다.

[.console-output]
[source,bash]
----
Aloha from my-deployment-5dc67997c7-m7z9f
----

NOTE: [ctrl+c]를 입력하여 pod 명령어 실행(쉘) 모드를 종료할 수 있습니다.



*다른 터미널(Terminal#3)* 에서 'my-deployment'에 대한 서비스를 배포하세요.:

* *Terminal#3에서 수행*

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project log-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "log-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project log-%userid%` : 현재 활성화된 컨텍스트의 기본 프로젝트를 log-%userid%로 변경합니다.


[#create-service]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Service
metadata:
  name: the-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
EOF
----

해당 서비스를 반복적으로 curl 하세요.:


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(oc get service the-service -o jsonpath="{.spec.clusterIP}")
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PORT=$(oc get service the-service -o jsonpath="{.spec.ports[*].port}")
----


[#poll-endpoint]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
while true
do curl $IP:$PORT
sleep 0.8
done
----


그런 다음 -f 옵션을 사용하여 Pod의 실시간 로그를 봅니다.
(이전 명령어를 취소하지 않았다면 실시간 로그가 출력되는 것을 볼 수 있습니다.)


* *Terminal#1에서 수행*

[#logs-log-deployment-follow]
[.console-input]
[source, bash]
----
oc logs my-deployment-5dc67997c7-m7z9f -f
----

NOTE: `-f` 매개변수를 사용하여 로그를 실시간으로 출력할 수 있습니다.

IMPORTANT: pod 이름( my-deployment-5dc67997c7-m7z9f)은 각 실습 클러스터에서 조회 된 값으로 변경하여 입력하세요.


[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Aloha from my-deployment-59cb8f6c56-bfrg7 124
Aloha from my-deployment-59cb8f6c56-bfrg7 125
Aloha from my-deployment-59cb8f6c56-bfrg7 126
Aloha from my-deployment-59cb8f6c56-bfrg7 127
Aloha from my-deployment-59cb8f6c56-bfrg7 128
Aloha from my-deployment-59cb8f6c56-bfrg7 129
Aloha from my-deployment-59cb8f6c56-bfrg7 130
Aloha from my-deployment-59cb8f6c56-bfrg7 131
Aloha from my-deployment-59cb8f6c56-bfrg7 132
Aloha from my-deployment-59cb8f6c56-bfrg7 133
Aloha from my-deployment-59cb8f6c56-bfrg7 134
Aloha from my-deployment-59cb8f6c56-bfrg7 135
Aloha from my-deployment-59cb8f6c56-bfrg7 136
Aloha from my-deployment-59cb8f6c56-bfrg7 137
Aloha from my-deployment-59cb8f6c56-bfrg7 138
Aloha from my-deployment-59cb8f6c56-bfrg7 139
Aloha from my-deployment-59cb8f6c56-bfrg7 140
----



NOTE: [ctrl+c]를 입력하여 반복 로그 조회를 종료할 수 있습니다.





== Clean Up

[#clean-up]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete service the-service
----

[#clean-up]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete deployment my-deployment
----
