= Service Magic

네임스페이스 생성:

* *Terminal#1에서 작업*

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc new-project funstuff-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
namespace/funstuff-%userid% created
----

NOTE: `oc new-project funstuff-%userid%` : funstuff-%userid%라는 새 프로젝트(네임스페이스)를 생성합니다.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project funstuff-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "funstuff-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project funstuff-%userid%` : 현재 활성화된 컨텍스트의 기본 네임스페이스를 funstuff-%userid%로 변경합니다.



== mypython-deployment 배포

[#deploy-mypython]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypython-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypython
  template:
    metadata:
      labels:
        app: mypython
    spec:
      containers:
      - name: mypython
        image: quay.io/rhdevelopers/mypython:v1
        ports:
        - containerPort: 8000
EOF
----

== mygo-deployment 배포

[#deploy-mygo]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mygo
  template:
    metadata:
      labels:
        app: mygo
    spec:
      containers:
      - name: mygo
        image: quay.io/rhdevelopers/mygo:v1
        ports:
        - containerPort: 8000
EOF
----

== mynode-deployment 배포

[#deploy-mynode]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynode-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynode
  template:
    metadata:
      labels:
        app: mynode
    spec:
      containers:
      - name: mynode
        image: quay.io/rhdevelopers/mynode:v1
        ports:
        - containerPort: 8000
EOF
----

NOTE: 아래의 명령어는 별도의 터미널에서 작업합니다.


* *Terminal#2에서 작업*

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project funstuff-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "funstuff-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project funstuff-%userid%` : 현재 활성화된 컨텍스트의 기본 네임스페이스를 funstuff-%userid%로 변경합니다.


[#labels-service-magic]
[.console-input]
[source, bash]
----
watch oc get pods --show-labels
----

[.console-output]
[source,bash]
----
NAME                                   READY   STATUS    RESTARTS   AGE     LABELS
mygo-deployment-6d944c5c69-kcvmk       1/1     Running   0          2m11s   app=mygo,pod-template-hash=6d944c5c69
mynode-deployment-fb5457c5-hhz7h       1/1     Running   0          2m1s    app=mynode,pod-template-hash=fb5457c5
mypython-deployment-6874f84d85-2kpjl   1/1     Running   0          3m53s   app=mypython,pod-template-hash=6874f84d85
----

NOTE: 배포된 pod를 label값을 포함하여 실시간으로 확인합니다. 배포되어 있는 pod들은 inservice=mypods label 값이 없는 것을 확인할 수 있습니다.


* *Terminal#1에서 작업*

`inservice=mypods label` 값을 참조하는 Service를 배포하세요.:

[#deploy-myservice]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: mystuff
spec:
  ports:
  - name: http
    port: 8000
  selector:
    inservice: mypods
EOF
----

[#describe-myservice-service-magic]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe service my-service
----

NOTE: `my-service` Service의 정보를 확인합니다.


[#get-endpoints-myservice]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get endpoints
----

[.console-output]
[source,bash]
----
NAME         ENDPOINTS   AGE
my-service   <none>      2m6s
----

[#get-endpoints1]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get endpoints my-service -o json | jq '.subsets[].addresses[].ip'
----

[.console-output]
[source,bash]
----
jq: error (at <stdin>:18): Cannot iterate over null (null)
----
NOTE: 현재 Service가 선택할 수 있는 Pod가 없기 때문에 IP 조회가 실패합니다.


Service의 Cluster IP를 가져옵니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(oc get service my-service -o jsonpath="{.spec.clusterIP}")
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PORT=$(oc get service my-service -o jsonpath="{.spec.ports[*].port}")
----


Poll the endpoint:

[#poll-endpoint]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
while true
do curl $IP:$PORT
sleep 0.8
done
----


[.console-output]
[source,bash]
----
curl: (7) Failed to connect to 35.224.233.213 port 8000: Connection refused
curl: (7) Failed to connect to 35.224.233.213 port 8000: Connection refused
----

NOTE: 현재 Service가 참조하는 label을 가진 Pod가 없기 때문에 curl은 실패합니다.

그럼 이제 Service가 Pod들을 바라볼 수 있도록 Pod에 label을 달아주도록 하겠습니다.

* *Terminal#3에서 작업*

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project funstuff-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "funstuff-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project funstuff-%userid%` : 현재 활성화된 컨텍스트의 기본 네임스페이스를 funstuff-%userid%로 변경합니다.

아래 명령어를 통해 현재 Service가 참조하고 있는 label(inservice=mypods)을 Python Pod(app=mypython)에 설정합니다.

[#label-mypython]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc label pod -l app=mypython inservice=mypods
----


* *Terminal#1에서 확인*

Poll the endpoint:

[#poll-endpoint]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
while true
do curl $IP:$PORT
sleep 0.8
done
----

[.console-output]
[source,bash]
----
curl: (7) Failed to connect to 35.224.233.213 port 8000: Connection refused
Python Hello on mypython-deployment-6874f84d85-2kpjl
Python Hello on mypython-deployment-6874f84d85-2kpjl
Python Hello on mypython-deployment-6874f84d85-2kpjl
----

NOTE: 현재 Service가 참조하는 label(inservice=mypods)을 가진 Python Pod(app=mypython)에서 응답하기 시작합니다.
NOTE: 응답까지 조금 시간이 걸릴 수 있습니다. 


이어서 다른 Pod에도 label을 추가해봅니다.

* *Terminal#3에서 작업*

[#label-mynode]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc label pod -l app=mynode inservice=mypods
----

NOTE: 현재 Service가 참조하는 label(inservice=mypods)을 Nodejs Pod(app=mynode)에도 설정합니다.

* *Terminal#1에서 확인*

Poll the endpoint:

[#poll-endpoint]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
while true
do curl $IP:$PORT
sleep 0.8
done
----

[.console-output]
[source,bash]
----
Python Hello on mypython-deployment-6874f84d85-2kpjl
Python Hello on mypython-deployment-6874f84d85-2kpjl
Node Hello on mynode-deployment-fb5457c5-hhz7h 0
Node Hello on mynode-deployment-fb5457c5-hhz7h 1
Python Hello on mypython-deployment-6874f84d85-2kpjl
Python Hello on mypython-deployment-6874f84d85-2kpjl
Python Hello on mypython-deployment-6874f84d85-2kpjl
----

NOTE: 현재 Service가 참조하는 label(inservice=mypods)을 가지게 된 Nodejs Pod(app=mynode)에서도 응답하기 시작합합니다.



* *Terminal#3에서 작업*

[#label-mygo]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc label pod -l app=mygo inservice=mypods
----

NOTE: 현재 Service가 참조하는 label(inservice=mypods)을 Golang Pod(app=mygo)에 설정합니다.


* *Terminal#1에서 확인*

Poll the endpoint:

[#poll-endpoint]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
while true
do curl $IP:$PORT
sleep 0.8
done
----

[.console-output]
[source,bash]
----
Node Hello on mynode-deployment-fb5457c5-hhz7h 59
Node Hello on mynode-deployment-fb5457c5-hhz7h 60
Go Hello on mygo-deployment-6d944c5c69-kcvmk
Python Hello on mypython-deployment-6874f84d85-2kpjl
Python Hello on mypython-deployment-6874f84d85-2kpjl
----

NOTE: 현재 Service가 참조하는 label(inservice=mypods)을 가지게 된 Golang Pod(app=mygo)에서도 응답합니다.

각각 다른 언어로 작성된 애플리케이션 파드들이 동일한 endpoint(Service IP)를 통해 같이 응답하고 있음을 확인할 수 있습니다.

* *Terminal#3에서 확인*

[#get-endpoints2]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get endpoints my-service -o json | jq '.subsets[].addresses[].ip'
----

[.console-output]
[source,bash]
----
"10.130.2.43"
"10.130.2.44"
"10.130.2.45"
----

NOTE: 위 명령어를 통해 Service가 트래픽을 전달하고 있는 pod 3개의 IP가 모두 확인됩니다.


파드들의 IP를 다시 확인하세요.

[#pod-ips]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get pods -o wide
----


Service에 연결된 Pod 중 `mypython` Pod를 제거합니다.

[#remove-label]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc label pod -l app=mypython inservice-
----

[#get-endpoints3]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get endpoints my-service -o json | jq '.subsets[].addresses[].ip'
----

[.console-output]
[source,bash]
----
"10.130.2.44"
"10.130.2.45"
----

NOTE: Label이 제거된 Pod의 IP를 제외한 pods IP만 조회됩니다.


== Clean Up

실습을 완료하였으면 프로젝트를 삭제합니다. 
(프로젝트를 통째로 삭제하는 경우 약간 시간이 걸릴 수 있습니다.)

[#clean-up]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete project funstuff-%userid%
----
