= Rolling updates

IMPORTANT: 이 실습은 직전의 `Resources and Limits` 실습 환경을 이어서 사용합니다.

올바른 네임스페이스에 있는지 확인하세요.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project resource-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "resource-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project resource-%userid%` : 현재 활성화된 컨텍스트의 기본 네임스페이스를 resource-%userid%로 변경합니다.




[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get deployment
----

[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get pod
----

[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get service
----


[TIP,subs="attributes+,+macros"]
====
이전 실습 `Resources and Limits` 에서 바로 넘어왔다면 필요한 Pod 및 배포 그리고 서비스가 이미 생성성되어 있어야 합니다. +
그렇지 않은 경우 다음 명령을 실행하여 필요한 요소를 `resource-%userid%` 에 배포해야 합니다.
====

* *Terminal#1에서 작업*

Pod를 지켜보세요.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project resource-%userid%
----


[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "resource-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project resource-%userid%` : 현재 활성화된 컨텍스트의 기본 네임스페이스를 resource-%userid%로 변경합니다.



[#sysresources-sane-limit-resource]
[.console-input]
[source, bash]
----
watch -n 1 -- oc get pods
----




* *Terminal#2에서 작업* 

반복적으로 서비스에 curl을 시도하세요.


[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project resource-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "resource-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project resource-%userid%` : 현재 활성화된 컨텍스트의 기본 네임스페이스를 resource-%userid%로 변경합니다.


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(kubectl get service myboot -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PORT=$(kubectl get service myboot -o jsonpath="{.spec.ports[*].port}")
----


Poll the endpoint:

[#poll-endpoint]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
while true
do curl $IP:$PORT
sleep 0.8
done
----






* *Terminal#3에서 작업*

명령을 실행합니다.



[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project resource-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "resource-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project resource-%userid%` : 현재 활성화된 컨텍스트의 기본 네임스페이스를 resource-%userid%로 변경합니다.

deployment의 정보를 확인합니다.


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe deployment myboot
----


// The .no-query-replace tells the course ui to not attempt to replace tokens between % %
[.no-query-replace]
[.console-output]
[source,bash]
----
.
.
.
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
.
.
.
----

NOTE: `StrategyType` 옵션에는 `RollingUpdate` 및 `Recreate` 가 포함됩니다.



replicas를 변경합니다.


[#edit-deployment-replicas-rolling]
[.console-input]
[source, bash]
----
oc edit deployment myboot
----


"replicas" 항목을 찾습니다.

[.console-output]
[source,yaml]
----
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myboot
----

replicas 값을  "2"로 변경합니다.

[.console-output]
[source, yaml]
----
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myboot
----

TIP: 아래와 같은 순서로 작업하세요. +
1. "replicas: 1"에서 숫자 1에 커서를 두고 `i` 키를 눌러 입력모드로 전환하세요. +
2. `방향키` 와 `백스페이스` 를 이용하여 숫자 "1"을 삭제 후, "2"를 입력하세요. +
3. `esc` 키를 눌러 입력모드를 종료하세요. +
4. `:` 키를 눌러 커멘드라인 모드로 전환하세요. +
5. `wq` 를 입력한 후 `enter` 키를 누르세요.

TIP: 편집기의 단축키는 아래와 같습니다. +
*`i`* : 입력 모드로 전환(커서 앞에서 입력 시작) +
- 입력모드 전환 후, 방향키로 커서를 이동 및 `백스페이스` 로 문자 삭제 가능 +
*`:`* : 커멘드라인 모드로 전환 +
(커맨드라인 모드에서) *`w`* : 파일 저장 +
(커맨드라인 모드에서) *`q`* : 파일 종료 +

편집기를 저장하고 닫으면 새 파드가 활성화됩니다.

[#edit-deployment-replicas-get-pod-rolling]
[.console-input]
[source, bash]
----
oc get pods
----

[.console-output]
[source,bash]
----
NAME                     READY   STATUS    RESTARTS   AGE
myboot-d78fb6d58-2fqml   1/1     Running   0          25s
myboot-d78fb6d58-ljkjp   1/1     Running   0          3m
----

배포와 관련된 이미지를 변경합니다.

[#edit-deployment-v2-rolling]
[.console-input]
[source, bash]
----
oc edit deployment myboot
----

image 속성 부분을 찾으세요.:

[source, yaml]
----
    spec:
      containers:
      - image: quay.io/rhdevelopers/myboot:v1
        imagePullPolicy: IfNotPresent
        name: myboot
----

그리고 `myboot:v2` 이미지를 변경하세요.:

[source, yaml]
----
    spec:
      containers:
      - image: quay.io/rhdevelopers/myboot:v2
        imagePullPolicy: IfNotPresent
        name: myboot
----

TIP: 아래와 같은 순서로 작업하세요. +
1. "image: quay.io/rhdevelopers/myboot:v1"에서 숫자 1에 커서를 두고 `i` 키를 눌러 입력모드로 전환하세요. +
2. `방향키` 와 `백스페이스` 를 이용하여 숫자 "1"을 삭제 후, "2"를 입력하세요. +
3. `esc` 키를 눌러 입력모드를 종료하세요. +
4. `:` 키를 눌러 커멘드라인 모드로 전환하세요. +
5. `wq` 를 입력한 후 `enter` 키를 누르세요.

TIP: 편집기의 단축키는 아래와 같습니다. +
*`i`* : 입력 모드로 전환(커서 앞에서 입력 시작) +
- 입력모드 전환 후, 방향키로 커서를 이동 및 `백스페이스` 로 문자 삭제 가능 +
*`:`* : 커멘드라인 모드로 전환 +
(커맨드라인 모드에서) *`w`* : 파일 저장 +
(커맨드라인 모드에서) *`q`* : 파일 종료 +

[#edit-deployment-v2-get-pod-rolling]
[.console-input]
[source, bash]
----
oc get pods
----

[.console-output]
[source,bash]
----
NAME                      READY   STATUS              RESTARTS   AGE
myboot-7fbc4b97df-4ntmk   1/1     Running             0          9s
myboot-7fbc4b97df-qtkzj   0/1     ContainerCreating   0          0s
myboot-d78fb6d58-2fqml    1/1     Running             0          3m29s
myboot-d78fb6d58-ljkjp    1/1     Terminating         0          8m
----

Terminal#2의 출력을 확인하세요.

[.console-output]
[source,bash]
----
Aloha from Spring Boot! 211 on myboot-d78fb6d58-2fqml
Aloha from Spring Boot! 212 on myboot-d78fb6d58-2fqml
Bonjour from Spring Boot! 0 on myboot-7fbc4b97df-4ntmk
Bonjour from Spring Boot! 1 on myboot-7fbc4b97df-4ntmk
----

배포 상태를 확인합니다.

[#rollout-v2-rolling]
[.console-input]
[source, bash]
----
oc rollout status deployment myboot
----

[.console-output]
[source,bash]
----
deployment "myboot" successfully rolled out
----

새로운 Replicasets가 있는 것을 확인하세요.

[#rs-v2-rolling]
[.console-input]
[source, bash]
----
oc get rs
----

[.console-output]
[source,bash]
----
NAME                DESIRED   CURRENT   READY   AGE
myboot-7fbc4b97df   2         2         2       116s
myboot-d78fb6d58    0         0         0       10m
----

Deployment 정보를 확인하세요.:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe deployment myboot
----


그리고 이벤트 섹션을 확인해 보세요.:

[.console-output]
[source,bash]
----
...
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  16m    deployment-controller  Scaled up replica set myboot-d78fb6d58 to 1
  Normal  ScalingReplicaSet  6m15s  deployment-controller  Scaled up replica set myboot-d78fb6d58 to 2
  Normal  ScalingReplicaSet  2m55s  deployment-controller  Scaled up replica set myboot-7fbc4b97df to 1
  Normal  ScalingReplicaSet  2m46s  deployment-controller  Scaled down replica set myboot-d78fb6d58 to 1
  Normal  ScalingReplicaSet  2m46s  deployment-controller  Scaled up replica set myboot-7fbc4b97df to 2
  Normal  ScalingReplicaSet  2m37s  deployment-controller  Scaled down replica set myboot-d78fb6d58 to 0
----

다음 명령을 실행하여 배포와 관련된 개정을 나열할 수 있습니다.
[#rollout-history]
[.console-input]
[source, bash]
----
oc rollout history deployment/myboot
----

[.console-output]
[source,bash]
----
deployment.apps/myboot 
REVISION  CHANGE-CAUSE
1         <none>
2         <none>
----

다음 명령을 사용하여 이전 버전전으로 롤백할 수 있습니다.

[#describe-rollback-rolling]
[.console-input]
[source, bash]
----
oc rollout undo deployment/myboot
----

그리고 애플리케이션이 Aloha로 롤백됩니다.

[.console-output]
[source,bash]
----
Bonjour from Spring Boot! 501 on myboot-7fbc4b97df-qtkzj
Bonjour from Spring Boot! 502 on myboot-7fbc4b97df-qtkzj
Aloha from Spring Boot! 0 on myboot-d78fb6d58-vnlch
----

