= 애플리케이션 구성 외부화

== Kubernetes 애플리케이션 구성
애플리케이션이 기존 이미지를 사용하여 Kubernetes에서 실행되는 경우 애플리케이션은 기본 구성을 사용합니다. 이 작업은 테스트를 위한 것입니다. 그러나 프로덕션 환경의 경우 배포하기 전에 애플리케이션을 사용자 지정해야 할 수 있습니다.

Kubernetes에서는 JSON 및 YAML 형식의 매니페스트를 사용하여 각 애플리케이션에 대해 의도한 구성을 지정할 수 있습니다. 애플리케이션의 이름, 레이블, 이미지 소스, 스토리지, 환경 변수 등을 정의할 수 있습니다.

애플리케이션에서 파일 조합을 구성해야 하는 경우가 있습니다. 예를 들어 생성 시에는 데이터베이스 배포에 데이터베이스 및 데이터가 미리 로드되어 있어야 합니다. 일반적으로는 환경 변수, 외부 파일 또는 명령줄 인수를 사용하여 애플리케이션을 구성합니다. 애플리케이션이 실행되는 환경에서 컨테이너 이미지, 외부 파일, 환경 변수를 사용할 수 있는 경우 이 구성 외부화 프로세스를 통해 여러 환경에 걸쳐 애플리케이션을 이식할 수 있습니다.

Kubernetes는 구성 맵 및 시크릿을 사용하여 애플리케이션의 구성을 외부화하는 메커니즘을 제공합니다.

구성 맵을 사용하여 컨테이너에 구성 데이터를 삽입할 수 있습니다. 네임스페이스가 지정된 ConfigMap (구성 맵) 오브젝트는 컨테이너에 구성 데이터를 삽입하는 방법을 제공하여 컨테이너의 플랫폼 독립성을 유지하는 데 도움이 됩니다. 이러한 오브젝트는 개별 특성 등의 세분화된 정보나 전체 구성 파일 또는 JSON Blob(JSON 섹션) 등의 개괄적인 정보를 저장할 수 있습니다. 구성 맵의 정보는 보호하지 않아도 됩니다.

애플리케이션에서 중요한 정보에 액세스해야 하는 경우가 종종 있습니다. 예를 들어 백엔드 웹 애플리케이션에서는 데이터베이스를 쿼리하기 위해 데이터베이스 자격 증명에 액세스해야 합니다. Kubernetes 및 OpenShift에서는 시크릿을 사용하여 중요한 정보를 보관합니다. 예를 들어 시크릿을 사용하여 다음 유형의 중요한 정보를 저장할 수 있습니다.

* 암호

* 중요한 구성 파일

* SSH 키 또는 OAuth 토큰과 같은 외부 리소스에 대한 자격 증명

시크릿은 네임스페이스가 지정된 오브젝트이며 모든 유형의 데이터를 저장할 수 있습니다. 시크릿의 데이터는 Base64로 인코딩되며 일반 텍스트로 저장되지 않습니다. 시크릿 데이터는 암호화되지 않습니다. Base64 형식의 시크릿을 디코딩하여 원본 데이터에 액세스할 수 있습니다. 

Kubernetes 및 OpenShift는 다음 유형의 시크릿을 지원합니다.

* 불투명 시크릿: 임의의 값을 포함하고 키 이름 또는 값에 대한 규칙을 준수하도록 검증되지 않은 불투명 시크릿 저장소 키 및 값 쌍입니다.

* 서비스 계정 토큰: Kubernetes API에 인증하는 애플리케이션의 토큰 자격 증명을 저장합니다.

* 기본 인증 시크릿: 기본 인증에 필요한 자격 증명을 저장합니다. 시크릿 개체의 데이터 매개 변수에는 Base64 포맷으로 인코딩된 사용자 및 암호 키가 포함되어야 합니다.

* SSH 키: SSH 인증에 사용되는 데이터를 저장합니다.

* TLS 인증서: TLS에 사용되는 인증서 및 키를 저장합니다.

* Docker 구성 시크릿: 컨테이너 이미지 레지스트리에 액세스하기 위한 자격 증명을 저장합니다.

특정 시크릿 리소스 유형에 정보를 저장하는 경우 Kubernetes는 데이터가 시크릿 유형에 맞는지 확인합니다.



= ConfigMap

ConfigMap은 애플리케이션 구성을 외부화할 수 있는 Kubernetes 리소스입니다.

*_앱 구성은 배포마다 달라질 수 있는 모든 것입니다(스테이징, 프로덕션, 개발자 환경 등)._*

https://12factor.net/config[12 Factor Apps]

== 환경 변수(Environment Variables)

MyRESTController.java에는 환경을 살펴보는 작은 코드 덩어리가 포함되어 있습니다.

[source,java]
----
   @RequestMapping("/configure")
   public String configure() {
        String databaseConn = environment.getProperty("DBCONN","Default");
        String msgBroker = environment.getProperty("MSGBROKER","Default");
        String hello = environment.getProperty("GREETING","Default");
        String love = environment.getProperty("LOVE","Default");
        return "Configuration: \n"
            + "databaseConn=" + databaseConn + "\n"
            + "msgBroker=" + msgBroker + "\n"
            + "hello=" + hello + "\n"
            + "love=" + love + "\n";
   }
----

환경 변수는 배포 수준에서 조작할 수 있습니다.  변경사항으로 인해 Pod 재배포가 발생합니다.



네임스페이스를 생성 후, 올바른 네임스페이스에 있는지 확인하세요.


[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc new-project ev-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
namespace/ev-%userid% created
----

NOTE: `oc new-project ev-%userid%` : ev-%userid%라는 새 프로젝트(네임스페이스)를 생성합니다.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project ev-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "ev-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project ev-%userid%` : 현재 활성화된 컨텍스트의 기본 네임스페이스를 ev-%userid%로 변경합니다.



네임스페이스에서 아무것도 실행되고 있지 않은지 확인하세요.

[#no-resources-resource]
[.console-input]
[source, bash]
----
oc get all
----

[.console-output]
[source,bash]
----
No resources found in myspace namespace.
----





Deploy `myboot`:

[#deploy-myboot-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc create -f apps/kubefiles/myboot-deployment.yml
cat <<EOF | oc create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myboot
  name: myboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myboot
  template:
    metadata:
      labels:
        app: myboot
    spec:
      containers:
      - name: myboot
        image: quay.io/rhdevelopers/myboot:v1
        ports:
          - containerPort: 8080
EOF
----


Service를 배포하세요:

[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc create -f -
apiVersion: v1
kind: Service
metadata:
  name: myboot
  labels:
    app: myboot    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: myboot
  type: LoadBalancer
EOF
----



그리고 Pod 상태를 확인하세요.


[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get pod
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(kubectl get service myboot -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PORT=$(kubectl get service myboot -o jsonpath="{.spec.ports[*].port}")
----


애플리케이션에 구성내용을 요청하세요.


[#get-config-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-66d7d57687-jsbz7
databaseConn=Default
msgBroker=Default
greeting=Default
love=Default
----

NOTE : 현재 설정되어 있는 Application의 환경 변수값을 확인 할 수 있습니다.



== 환경 변수 설정

[#set-env-vars]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc set env deployment/myboot GREETING="namaste" \
  LOVE="Aloha" \
  DBCONN="jdbc:sqlserver://45.91.12.123:1443;user=MyUserName;password=*****;"
----

Pod가 다시 시작하는 모습을 확인하세요.

[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get pod
----


[.console-output]
[source,bash]
----
NAME                      READY   STATUS        RESTARTS   AGE
myboot-66d7d57687-jsbz7   1/1     Terminating   0          5m
myboot-785ff6bddc-ghwpc   1/1     Running       0          13s
----


애플리케이션에 구성내용을 요청하세요.


[#get-config2-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-5fd9dd9c59-58xbh
databaseConn=jdbc:sqlserver://45.91.12.123:1443;user=MyUserName;password=*****;
msgBroker=Default
greeting=namaste
love=Aloha
----

NOTE: 환경변수 값이 변경된 것을 확인할 수 있습니다.

배포의 정보를 확인합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe deployment myboot
----



[.console-output]
[source,bash]
----
...
  Containers:
   myboot:
    Image:      quay.io/burrsutter/myboot:v1
    Port:       8080/TCP
    Host Port:  0/TCP
    Environment:
      GREETING:  namaste
      LOVE:      Aloha
      DBCONN:    jdbc:sqlserver://45.91.12.123:1443;user=MyUserName;password=*****;
    Mounts:      <none>
  Volumes:       <none>
...  
----

환경 변수를 제거합니다.

[#remove-env-vars-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc set env deployment/myboot GREETING- \
  LOVE- \
  DBCONN-
----

그리고 제거되었는지 확인합니다.

[#get-config3-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-66d7d57687-xkgw6
databaseConn=Default
msgBroker=Default
greeting=Default
love=Default
----





=== Clean Up

[#clean-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete deployment myboot
----




==  ConfigMap 생성하기

[#create-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc create configmap my-config --from-literal=GREETING=jambo --from-literal=LOVE=Amour
----


configmap의 리스트를 확인하고, 생성된 configmap이 있는지 확인합니다.
TIP: 명령어 사용시,  `configmap` 은 줄여서 `cm` 으로 사용할 수 있습니다.

[#get-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get cm
----


[#get-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get cm my-config
----

생성된 configmap의 값을 json 포맷으로 확인합니다.

[#get-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get cm my-config -o json
----


[.console-output]
[source,bash]
----
...
    "data": {
        "GREETING": "jambo",
        "LOVE": "Amour"
    },
    "kind": "ConfigMap",
...    
----

또는 `ConfigMap` 개체를 `describe` 할 수 있습니다.

[#describe-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe cm my-config
----

[.console-output]
[source,bash]
----
Name:         my-config
Namespace:    myspace
Labels:       <none>
Annotations:  <none>

Data
====
GREETING:
====
jambo
LOVE:
====
Amour
Events:  <none>
----

.'kubectl edit'을 사용하여 리소스 보기
****
대용량 파일의 경우 'kubectl edit'을 사용하는 것이 클러스터의 리소스를 보는 데 더 편리할 수 있습니다.  우리의 경우 다음을 실행하여 구성 맵을 볼 수 있습니다(그리고 모든 변경 사항을 중단합니다!).

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc edit cm my-config
----
****

이제 `ConfigMap`에 대한 요청을 사용하여 앱을 배포합니다.

[#deploy-myboot-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myboot
  name: myboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myboot
  template:
    metadata:
      labels:
        app: myboot
    spec:
      containers:
      - name: myboot
        image: quay.io/rhdevelopers/myboot:v1  
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: my-config
EOF
----


NOTE: `spec` > `containers` > `envFom` 에 configmap이 포함된 것을 확인할 수 있습니다.




그리고 구성 Endpoint를 가져옵니다.

[#get-config4-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-84bfcff474-x6xnt
databaseConn=Default
msgBroker=Default
greeting=jambo
love=Amour
----

그리고 `ConfigMap`을 다시 생성하여 다른 속성 파일로 전환합니다.


[#delete-pod-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete cm my-config
----

[#delete-pod-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc create configmap my-config --from-literal=DBCONN=jdbc:sqlserver://123.123.123.123:1443 --from-literal=user=MyUserName --from-literal=password=***** --from-literal=MSGBROKER=tcp://localhost:61616?jms.useAsyncSend=true
----

[#delete-pod-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete pod -l app=myboot --wait=false
----

NOTE: pod는 deployment/replicaset에서 관리되고 있으므로, 삭제되는 즉시 재생성 됩니다. 


구성 Endpoint를 확인합니다.

[#get-config5-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-694954fc6d-nzdvx
databaseConn=jdbc:sqlserver://123.123.123.123:1443;user=MyUserName;password=*****;
msgBroker=tcp://localhost:61616?jms.useAsyncSend=true
hello=Default
love=Default
----

ConfigMap을 재미있게 즐길 수 있는 방법은 훨씬 더 많습니다.  핵심 문서에서는 배포 대신 Pod 사양을 조작하도록 되어 있지만 결과는 기본적으로 동일합니다.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap


== Clean Up

[#clean-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete deployment myboot
oc delete cm my-config
oc delete service myboot
----
