
= ConfigMap


Kubernetes는 애플리케이션을 실행할 때 필요한 설정 데이터를 컨테이너 이미지와 분리하여 관리하는 기능으로서 **ConfigMap(구성맵)**과 **Secret(시크릿)**이라는 구성요소를 가지고 있습니다. 
ConfigMap에는 설정 파일이나 환경 변수 같은 일반적인 https://12factor.net/config[설정 데이터]를 저장하고, Secret에는 비밀번호, API 키, 인증서 같은 민감한 정보를 안전하게 저장할 수 있습니다.

물론 애플리케이션의 환경변수를 Deployment에 **직접** 설정하는 방법도 있지만, 아래와 같은 단점이 있습니다.
* 환경변수를 변경할 때마다 Deployment가 롤링 업데이트 됨
* 여러 Deployment에서 동일한 환경변수를 설정할 경우 일일이 수정해야 한다는 단점이 있습니다. 

대신 ConfigMap으로 설정 데이터를 분리하고 Deployment에서 이를 참조하도록 설정하면 아래와 같은 장점이 있습니다.
* 환경변수를 변경해도 Deployment가 자동 재시작되지 않음 (새로운 Pod에는 반영됨, 기존 Pod에도 반영하려면 수동으로 Pod를 재시작해야 함)
* 여러 Deployment에서 공유 가능
* 환경변수를 중앙에서 관리할 수 있어 유지보수 편리

이번 실습에서는 Deployment에 직접 환경변수를 설정하는 방법과 Configmap을 통해 설정하는 방법을 모두 확인해보겠습니다.

== 환경 변수(Environment Variables) 확인

새로운 프로젝트를 생성 후, 올바른 프로젝트에 있는지 확인하세요.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc new-project ev-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
namespace/ev-%userid% created
----

NOTE: `oc new-project ev-%userid%` : ev-%userid%라는 새 프로젝트(네임스페이스)를 생성합니다.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project ev-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "ev-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project ev-%userid%` : 현재 활성화된 컨텍스트의 기본 프로젝트를 ev-%userid%로 변경합니다.



프로젝트에서 아무것도 실행되고 있지 않은지 확인하세요.

[#no-resources-resource]
[.console-input]
[source, bash]
----
oc get all
----

[.console-output]
[source,bash]
----
No resources found in myspace namespace.
----



`myboot` 를 배포합니다.

[#deploy-myboot-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myboot
  name: myboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myboot
  template:
    metadata:
      labels:
        app: myboot
    spec:
      containers:
      - name: myboot
        image: quay.io/rhdevelopers/myboot:v1
        ports:
          - containerPort: 8080
EOF
----


Service를 배포합니다.

[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc create -f -
apiVersion: v1
kind: Service
metadata:
  name: myboot
  labels:
    app: myboot    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: myboot
EOF
----


그리고 Pod 상태를 확인합니다.


[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get pod
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(oc get service myboot -o jsonpath="{.spec.clusterIP}")
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PORT=$(oc get service myboot -o jsonpath="{.spec.ports[*].port}")
----

현재 배포되어 있는 myboot 애플리케이션에는 환경변수를 확인하는 작은 코드 덩어리가 포함되어 있습니다.

[source,java]
----
   @RequestMapping("/configure")
   public String configure() {
        String databaseConn = environment.getProperty("DBCONN","Default");
        String msgBroker = environment.getProperty("MSGBROKER","Default");
        String hello = environment.getProperty("GREETING","Default");
        String love = environment.getProperty("LOVE","Default");
        return "Configuration: \n"
            + "databaseConn=" + databaseConn + "\n"
            + "msgBroker=" + msgBroker + "\n"
            + "hello=" + hello + "\n"
            + "love=" + love + "\n";
   }
----

환경 변수는 Deployment 수준에서 변경할 수 있습니다. 변경 후 Pod가 재배포 됩니다.

먼저 아래 명령어를 통해 애플리케이션에 환경변수 값 조회를 요청합니다.


[#get-config-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-66d7d57687-jsbz7
databaseConn=Default
msgBroker=Default
greeting=Default
love=Default
----

NOTE : 현재 설정되어 있는 Application의 환경 변수값을 확인 할 수 있습니다.



== Deployment에 환경 변수 설정

[#set-env-vars]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc set env deployment/myboot GREETING="안녕하세요" \
  LOVE="Aloha" \
  DBCONN="jdbc:sqlserver://45.91.12.123:1443;user=MyUserName;password=*****;"
----

Pod가 다시 시작하는 모습을 확인합니다.

[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get pod
----


[.console-output]
[source,bash]
----
NAME                      READY   STATUS        RESTARTS   AGE
myboot-66d7d57687-jsbz7   1/1     Terminating   0          5m
myboot-785ff6bddc-ghwpc   1/1     Running       0          13s
----


애플리케이션에 환경변수 값 조회를 다시 요청합니다.

[#get-config2-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-6fc58bf96c-gw2cj
databaseConn=jdbc:sqlserver://45.91.12.123:1443;user=MyUserName;password=*****;
msgBroker=Default
greeting=안녕하세요
love=Aloha
----

NOTE: 환경변수 값이 변경된 것을 확인할 수 있습니다.

Deployment의 정보를 확인합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe deployment myboot
----



[.console-output]
[source,bash]
----
...
  Containers:
   myboot:
    Image:      quay.io/burrsutter/myboot:v1
    Port:       8080/TCP
    Host Port:  0/TCP
    Environment:
      GREETING:  안녕하세요
      LOVE:      Aloha
      DBCONN:    jdbc:sqlserver://45.91.12.123:1443;user=MyUserName;password=*****;
    Mounts:      <none>
  Volumes:       <none>
...  
----

환경 변수를 제거합니다.

[#remove-env-vars-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc set env deployment/myboot GREETING- \
  LOVE- \
  DBCONN-
----

그리고 제거되었는지 확인합니다.

[#get-config3-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-66d7d57687-xkgw6
databaseConn=Default
msgBroker=Default
greeting=Default
love=Default
----





=== Clean Up

생성했던 리소스를 삭제합니다. 

[#clean-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete deployment myboot
----




==  ConfigMap 생성

이번에는 Configmap을 통해 환경변수를 설정해보겠습니다.
먼저 Configmap을 생성합니다.

[#create-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc create configmap my-config --from-literal=GREETING=jambo --from-literal=LOVE=Amour
----


configmap의 리스트를 확인하고, 생성된 configmap이 있는지 확인합니다.
TIP: 명령어 사용시,  `configmap` 은 줄여서 `cm` 으로 사용할 수 있습니다.

[#get-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get cm
----


[#get-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get cm my-config
----

생성된 configmap의 값을 json 포맷으로 확인합니다.

[#get-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get cm my-config -o json
----


[.console-output]
[source,bash]
----
...
    "data": {
        "GREETING": "jambo",
        "LOVE": "Amour"
    },
    "kind": "ConfigMap",
...    
----

또는 `ConfigMap` 개체를 `describe` 할 수 있습니다.

[#describe-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe cm my-config
----

[.console-output]
[source,bash]
----
Name:         my-config
Namespace:    myspace
Labels:       <none>
Annotations:  <none>

Data
====
GREETING:
====
jambo
LOVE:
====
Amour
Events:  <none>
----

.'oc edit'을 사용하여 리소스 보기
****
대용량 파일의 경우 'oc edit'을 사용하는 것이 클러스터의 리소스를 보는 데 더 편리할 수 있습니다. 우리의 경우 다음을 실행하여 Configmap을 볼 수 있습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc edit cm my-config
----

편집 화면을 빠져나오려면 `:q`를 입력하고 ENTER를 누르세요.
****

이제 `ConfigMap` 를 참조하여 앱을 배포합니다.

[#deploy-myboot-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myboot
  name: myboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myboot
  template:
    metadata:
      labels:
        app: myboot
    spec:
      containers:
      - name: myboot
        image: quay.io/rhdevelopers/myboot:v1  
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: my-config
EOF
----


NOTE: `spec` > `containers` > `envFom` 에 configmap이 포함된 것을 확인할 수 있습니다.


그리고 환경변수수 Endpoint를 가져옵니다.

[#get-config4-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-84bfcff474-x6xnt
databaseConn=Default
msgBroker=Default
greeting=jambo
love=Amour
----

그리고 `ConfigMap`을 삭제 후 다른 설정값으로 다시 생성합니다.


[#delete-pod-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete cm my-config
----

[#delete-pod-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc create configmap my-config --from-literal=DBCONN=jdbc:sqlserver://123.123.123.123:1443 --from-literal=user=MyUserName --from-literal=password=***** --from-literal=MSGBROKER=tcp://localhost:61616?jms.useAsyncSend=true
----

[#delete-pod-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete pod -l app=myboot --wait=false
----

NOTE: pod는 deployment/replicaset에서 관리되고 있으므로, 삭제되는 즉시 재생성 됩니다. +
새롭게 생성되는 Pod는 새로운 configmap의 내용(configmap의 이름은 동일)을 참조하여 생성됩니다.


환경변수 Endpoint를 다시 확인합니다.

[#get-config5-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-694954fc6d-nzdvx
databaseConn=jdbc:sqlserver://123.123.123.123:1443;user=MyUserName;password=*****;
msgBroker=tcp://localhost:61616?jms.useAsyncSend=true
hello=Default
love=Default
----

ConfigMap은 다양하게 활용할 수 있습니다. kubernetes 문서에서는 Deployment 대신 Pod 사양을 조작하도록 되어 있지만 결과는 기본적으로 동일합니다.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap


== Clean Up

실습을 마쳤으면 생성했던 리소스를 삭제합니다. 

[#clean-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete deployment myboot 
oc delete cm my-config
oc delete service myboot
----
