= Secrets

**Secret(시크릿)**은 Kubernetes가 민감한 데이터를 저장하기 위해 제공하는 기본 구성요소입니다. 
Configmap과 다소 비슷하지만, Kubernetes 내부적으로 좀더 주의를 기울여 처리됩니다.

Secrets은 민감한 데이터(각종 비밀번호, 이미지 레지스트리 인증 정보, TLS 인증서 등)를 컨테이너화된 애플리케이션의 코드에 (안전하지 않게) 포함하지 않고도 사용할 수 있는 방법을 개발자에게 제공하기 위한 수단입니다. 

Secrets의 내용은 기본적으로 일반 텍스트로 표시되지 않습니다. 대신, Secrets 데이터는 base64로 인코딩되어 있으므로 읽으려면 디코딩해야 합니다.

이번 실습에서는 Deployment에 직접 환경변수를 설정하는 방법과 Configmap을 통해 설정하는 방법을 모두 확인해보겠습니다.

[WARNING]
====
Kubernetes API의 대부분 데이터와 마찬가지로 Secrets은 'etcd' 분산 데이터 저장소에 저장됩니다. 
이 데이터에 대한 접근은 클러스터의 RBAC에 의해 제한되지만, Secrets은 기본적으로 Kubernetes의 `etcd` 내에서 암호화되지 않고 저장됩니다. 
etcd 암호화는 https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/[이 링크^]를 참고하여 일반 Kubernetes에서 활성화할 수 있습니다. 
OpenShift를 사용하면 https://docs.openshift.com/container-platform/4.17/security/encrypting-etcd.html[이 링크^]에 따라 더욱 쉽게 etcd 암호화 기능을 활성화할 수 있습니다. 
====

== 사전 구성성

프로젝트를 생성 후, 올바른 프로젝트에 있는지 확인하세요.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc new-project secret-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
namespace/secret-%userid% created
----

NOTE: `oc new-project secret-%userid%` : secret-%userid%라는 새 프로젝트(네임스페이스)를 생성합니다.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project secret-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "secret-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project secret-%userid%` : 현재 활성화된 컨텍스트의 기본 프로젝트를 secret-%userid%로 변경합니다.



프로젝트에서 아무것도 실행되고 있지 않은지 확인하세요.

[#no-resources-resource]
[.console-input]
[source, bash]
----
oc get all
----

[.console-output]
[source,bash]
----
No resources found in myspace namespace.
----




`myboot`을 배포합니다.

[#deploy-myboot-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myboot
  name: myboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myboot
  template:
    metadata:
      labels:
        app: myboot
    spec:
      containers:
      - name: myboot
        image: quay.io/rhdevelopers/myboot:v1
        ports:
          - containerPort: 8080
EOF
----


Service를 배포합니다.

[#deploy-myboot-rolling]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc create -f -
apiVersion: v1
kind: Service
metadata:
  name: myboot
  labels:
    app: myboot    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: myboot
EOF
----



* *Terminal#2*

Pod에 Watch를 설정합니다.


[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project secret-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "secret-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project secret-%userid%` : 현재 활성화된 컨텍스트의 기본 프로젝트를 secret-%userid%로 변경합니다.



[.console-input]
[source,bash,subs="+macros,+attributes"]
----
watch oc get pods
----

* *Terminal#1에서 작업*

그 사이에 curl 요청을 보냅니다.


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(oc get service myboot -o jsonpath="{.spec.clusterIP}")
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PORT=$(oc get service myboot -o jsonpath="{.spec.ports[*].port}")
----



[#get-config-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Aloha from Spring Boot! 1 on myboot-7cbfbd9b89-dl2hv
----



== Creating Secrets

이전에는 `ConfigMap` 을 사용하여 데이터베이스 접속을 위한 인증정보(`user=MyUserName;password=pass:[*****]`)을 보유했습니다. 
`ConfigMap` 대신에 민감한 데이터를 좀 더 안전하게 저장하는 secret을 만들어 보겠습니다.

Kubernetes 및 OpenShift에서 지원하는 아래 Secret 유형 중, 데이터베이스 로그인에 사용할 수 있는 opaque 유형으로 Secret을 생성합니다.

***
* opaque: 특별한 형식 없이 임의의 키-값 데이터 저장, 일반적인 시크릿 데이터 저장 (가장 많이 사용)
* docker-registry: 컨테이너 이미지 레지스트리에 접근하기 위한 로그인 정보 저장
* tls: HTTPS 인증서 저장
* basic-auth: 유저 이름과 비밀번호 저장
* ssh-auth: SSH 키 저장
* service-account-token: 서비스 계정 토큰 저장, Kubernetes 내부 인증
***

`oc create secret generic` 명령어를 통해 opaque 유형의 Seceret을 생성할 수 있습니다.

[#create-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc create secret generic mysecret --from-literal=user='MyUserName' --from-literal=password='mypassword'
----

[#get-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get secrets
----

이제 다음과 유사한 출력이 생성됩니다.


[.console-output]
[source,bash]
----
NAME                       TYPE                                  DATA   AGE
builder-dockercfg-96ml5    kubernetes.io/dockercfg               1      3d6h
builder-token-h5g82        kubernetes.io/service-account-token   4      3d6h
builder-token-vqjqz        kubernetes.io/service-account-token   4      3d6h
default-dockercfg-bsnjr    kubernetes.io/dockercfg               1      3d6h
default-token-bl77s        kubernetes.io/service-account-token   4      3d6h
default-token-vlzsl        kubernetes.io/service-account-token   4      3d6h
deployer-dockercfg-k6npn   kubernetes.io/dockercfg               1      3d6h
deployer-token-4hb78       kubernetes.io/service-account-token   4      3d6h
deployer-token-vvh6r       kubernetes.io/service-account-token   4      3d6h
mysecret                   Opaque                                2      5s
----


`oc describe` 명령어를 사용해보아도, `ConfigMap` 이 아닌 `secret` 이므로 사용자 및 비밀번호가 즉시 표시되지 않습니다.

[#describe-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe secret mysecret
----

[.console-output]
[source,bash]
----
Name:         mysecret
Namespace:    myspace
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
password:  10 bytes
user:      10 bytes
----


Secret에 대해 충분한 권한이 있는 사용자는 다음 명령어를 통해 인코딩된 시크릿 값을 얻을 수 있습니다.

[#get-secret-cli-yaml-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get secret mysecret -o yaml
----


[source,yaml]
----
apiVersion: v1
data:
  password: bXlwYXNzd29yZA==
  user: TXlVc2VyTmFtZQ==
kind: Secret
metadata:
  creationTimestamp: "2020-03-31T20:19:26Z"
  name: mysecret
  namespace: myspace
  resourceVersion: "4944690"
  selfLink: /api/v1/namespaces/myspace/secrets/mysecret
  uid: e8c5f12e-bd71-4d6b-8d8c-7af9ed6439f8
type: Opaque
----

위의 비밀번호 필드 값을 아래 echo 명령에 복사하여 base64로 인코딩되었음을 증명하세요.

[#get-secret-cli-password-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
echo 'bXlwYXNzd29yZA==' | base64 --decode
----

[.console-output]
[source,bash]
----
mypassword
----



[TIP]
====
대신 다음 명령어를 사용할 수도 있습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
B64_PASSWORD=$(oc get secret mysecret -o jsonpath='{.data.password}')
echo "password:$B64_PASSWORD is decoded as $(echo $B64_PASSWORD | base64 --decode)"
----

====



그런 다음 사용자 이름에 대해 동일한 작업을 수행합니다.

[#get-secret-cli-username-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
echo 'TXlVc2VyTmFtZQ==' | base64 --decode
----

[.console-output]
[source,bash]
----
MyUserName
----


[TIP]
====
대신 다음 명령을 실행할 수 있습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
B64_DATA=$(oc get secret mysecret -o jsonpath='{.data.user}')
echo "username:$B64_DATA is decoded as $(echo $B64_DATA | base64 --decode)"
----

====


또는 `oc(kubectl)`을 사용하여 가져올 수 있습니다.

[#get-secret-kubectl-password-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get secret mysecret -o jsonpath='{.data.password}' | base64 --decode 
----



== Secrets 사용


새로 생성된 secret을 사용하는 Deployment를 살펴보겠습니다.

[.console-output]
[source,yaml,subs="+macros,+attributes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myboot
  name: myboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myboot
  template:
    metadata:
      labels:
        app: myboot
    spec:
      containers:
      - name: myboot
        image: quay.io/rhdevelopers/myboot:v1
        ports:
          - containerPort: 8080
        volumeMounts:          
          - name: mysecretvolume #<.>
            mountPath: /mystuff/secretstuff
            readOnly: true
      volumes:
        - name: mysecretvolume #<.>
          secret:
            secretName: mysecret
----
<.> Pod가 secret을 찾을 위치를 결정합니다.  Pod의 `/mystuff/secretstuff` 디렉토리에서 Secret 데이터를 찾을 수 있습니다.
<.> 컨테이너에서 Secret의 데이터를 읽을 수 있도록, 컨테이너에 마운트 할 'mysecretvolume'을 정의합니다. 이 경우 'mysecret'은 위에서 방금 만든 Secret입니다.

Deployment(Pod)에서 Secret을 사용할 수 있도록 해주는 방법 중 한 가지가 볼륨 마운트를 통해 secret을 제공하는 것입니다.

[source, yaml]
----
        volumeMounts:          
          - name: mysecretvolume
            mountPath: /mystuff/mysecretvolume
----

이 볼륨을 사용하도록 배포를 업데이트해 보겠습니다.

[#replace-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc replace -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myboot
  name: myboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myboot
  template:
    metadata:
      labels:
        app: myboot
    spec:
      containers:
      - name: myboot
        image: quay.io/rhdevelopers/myboot:v1
        ports:
          - containerPort: 8080
        volumeMounts:          
          - name: mysecretvolume 
            mountPath: /mystuff/secretstuff
            readOnly: true
      volumes:
        - name: mysecretvolume
          secret:
            secretName: mysecret
EOF
----

_Deployment가 업데이트되면_ 새로 생성된 Pod에 대해해 다음 명령어를 실행합니다.

[#print-secrets-volume-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PODNAME=$(oc get pod -l app=myboot --field-selector status.phase!=Terminating -o name)
oc exec $PODNAME -- ls -l /mystuff/secretstuff
oc exec $PODNAME -- cat /mystuff/secretstuff/password
----

결과는 다음과 같습니다.

[.console-output]
[source,bash]
----
total 0
lrwxrwxrwx. 1 root root 15 Jul 19 03:37 password -> ..data/password #<.>
lrwxrwxrwx. 1 root root 11 Jul 19 03:37 user -> ..data/user
mypassword #<.>
----
NOTE: <.> Secret 정의를 다시 참조하세요.  Secret의 `.data` 섹션 아래 각 필드는 마운트된 Secret을 나타내는 이 디렉터리의 파일이 되었습니다.
<.> `password` 파일의 값을 `cat`하면 위에서 정의한 `secret`의 `.data.password` 필드 값을 제공합니다.

[TIP]
====
또는 다음 명령을 실행하여 Pod에 rsh를 실행하고 둘러볼 수도 있습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PODNAME=$(oc get pod -l app=myboot --field-selector status.phase!=Terminating -o name)
oc exec -it $PODNAME -- /bin/bash
----
====


하지만 애플리케이션이 이 디렉터리에서 자격 증명을 찾는지 어떻게 알 수 있을까요?  애플리케이션에서(또는 속성을 통해) 하드코딩할 수 있지만 환경 변수를 통해 `/mystuff/mysecretvolume`을 통해 Pod에 경로를 제공하여 애플리케이션이 볼 위치를 알 수도 있습니다.

[TIP]
====
Secret을 환경 변수로 직접 노출하는 것도 가능하지만 이는 이 튜토리얼의 범위를 벗어납니다.
====

Secret에 대한 자세한 내용은 다음을 참조하세요.https://kubernetes.io/docs/concepts/configuration/secret/[here]

== Clean Up

[.console-input]
[source,bash]
----
oc delete deployment myboot
oc delete service myboot
----



