= Jobs & CronJobs
:watch-terminal: Terminal 2

대부분의 경우 Kubernetes는 지정된 수신 요청에 대한 응답을 제공하는 것이 목적인 "긴" 프로세스를 실행하는 플랫폼으로 사용하고 있습니다.
그러나 일부 로직(예: 데이터베이스 업데이트, 일괄 처리 등)를 실행하고 종료하는 것이 목적인 짧은 프로세스를 실행할 수도 있습니다.

Kubernetes Job은 일부 논리를 한 번만 실행하는 작업입니다. 
Kubernetes CronJob은 Cron 패턴에 따라 반복되는 작업입니다.


== 사전 구성


프로젝트를 생성 후, 올바른 프로젝트에 있는지 확인하세요.


[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc new-project jobs-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
namespace/jobs-%userid% created
----

NOTE: `oc new-project jobs-%userid%` : jobs-%userid%라는 새 프로젝트(네임스페이스)를 생성합니다.

[#kubectl-deploy-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project jobs-%userid%
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Now using project "jobs-%userid%" on server "https://172.30.0.1:443".
----

NOTE: `oc project jobs-%userid%` : 현재 활성화된 컨텍스트의 기본 프로젝트를 jobs-%userid%로 변경합니다.


프로젝트에서 아무것도 실행되고 있지 않은지 확인하세요.

[#no-resources-resource]
[.console-input]
[source, bash]
----
oc get all
----

[.console-output]
[source,bash]
----
No resources found in myspace namespace.
----


무슨 일이 일어나고 있는지 관찰할 수 있도록 다른 Terminal#2를 열고 다양한 작업을 실행할 때 어떤 일이 일어나는지 `watch` 해 보겠습니다.

* Terminal#2에서 작업

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
watch -n 1 "oc get pods -o wide \
  | awk '{print \$1 \" \" \$2 \" \" \$3 \" \" \$5 \" \" \$7}' | column -t"
----


TIP: `-o wide` 옵션을 사용하면 Pod가 예약된 노드를 볼 수 있습니다. +
줄이 너무 길어지는 것을 방지하기 위해 `awk`와 `column`을 사용하여 원하는 열만 가져오고 형식을 지정합니다.


== Jobs

[source, yaml]
----
apiVersion: batch/v1
kind: Job
metadata:
  name: whale-say-job #<.>
spec:
  template:
    spec:
      containers:
      - name: whale-say-container
        image: docker/whalesay
        command: ["cowsay","Hello DevNation"]
      restartPolicy: Never
----
<.> Job의 이름은 이 Job 정의에 의해 생성된 모든 Pod에서 'job-name' 라벨의 값으로 사용됩니다.


* *Terminal#1 에서 실행*

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc create -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: whale-say-job
spec:
  template:
    spec:
      containers:
      - name: whale-say-container
        image: docker/whalesay
        command: ["cowsay","Hello DevNation"]
      restartPolicy: Never
EOF
----

Terminal#2에 다음과 같은 출력이 생성됩니다(연속 새로 고침).

[.console-output]
[source,bash]
----
NAME                 READY  STATUS             AGE  NODE
whale-say-job-m8vxt  0/1    ContainerCreating  14s  devnation-m02
----

[.console-output]
[source,bash]
----
NAME                 READY  STATUS     AGE  NODE
whale-say-job-m8vxt  1/1    Running    80s  devnation-m02
----

[.console-output]
[source,bash]
----
NAME                 READY  STATUS     AGE  NODE
whale-say-job-m8vxt  0/1    Completed  85s  devnation-m02
----


다른 Kubernetes 리소스처럼 `Job` 리소스도 확인하실 수 있습니다.

* *Terminal#1에서 작업*

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get jobs
----

[.console-output]
[source,bash]
----
NAME            COMPLETIONS   DURATION   AGE
whale-say-job   1/1           20s        36s
----

Job은 Pod에 의해 실행되므로 `job` 실행의 출력을 얻으려면 Pod 로그의 출력만 얻으면 됩니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc logs \
  -l job-name=whale-say-job \#<.>
  --tail=-1 #<.>
----
<.> `-l` : 이를 통해 `whale-say-job`으로 설정된 `job-name`(위 참조) 라벨이 붙은 모든 Pod를 찾을 수 있습니다. 
<.> `--tail` 옵션은 로그 명령어에 (Pod의) 로그에서 끝에서부터 몇 줄을 반환할지 지정합니다. 이 작업용 Pod의 메시지에서 모든 재미난 내용을 확인할 수 있도록, -1로 설정하여 모든 줄을 반환하도록 했습니다.footnote:[일반적으로 --tail 옵션은 기본값으로 -1로 설정되어 있지만, 이는 _단일 특정 리소스_의 로그를 요청할 때만 해당됩니다. 라벨을 사용하여 로그를 요청할 경우처럼 여러 리소스의 로그를 반환할 가능성이 있는 상황에서는 각 리소스의 로그에서 반환되는 줄 수가 기본값으로 10줄로 제한됩니다.]

[.console-output]
[source,bash]
----
 _________________
< Hello DevNation >
 -----------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
----


=== Clean Up


* *Terminal#1에서 작업*

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete job whale-say-job
----





== CronJobs

CronJob은 Kubernetes 'CronJob' 리소스를 사용하여 정의됩니다.  'cronjob'이라는 이름은 Linux에서 유래되었으며 한 번 또는 반복적으로 실행되도록 예약된 일종의 배치 프로세스를 나타냅니다. 

[source, yaml]
----
apiVersion: batch/v1
kind: CronJob
metadata:
  name: whale-say-cronjob
spec:
  schedule: "* * * * *" #<.>
  jobTemplate:                   
    spec:                        
      template:    
        metadata:
          labels:
            job-type: whale-say #<.>              
        spec:
          containers:
          - name: whale-say-container
            image: docker/whalesay
            command: ["cowsay","Hello DevNation"]
          restartPolicy: Never
----
<.> 이 문자열은 작업이 1분마다 실행됨을 나타냅니다.
<.> 여기서는 `cronjob`에 의해 생성된 `jobs` 및 `pods` 에 적용할 자체 추가 라벨을 지정합니다.  'job-name' 라벨이 여전히 존재하더라도 모든 표시에 guid가 포함되어 있으므로 사전에 값이 무엇인지 예측할 수 없습니다.


* *Terminal#1 에서 수행*
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/whalesay-cronjob.yaml
cat <<EOF | oc create -f -
apiVersion: batch/v1
kind: CronJob
metadata:
  name: whale-say-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:                   
    spec:                        
      template:    
        metadata:
          labels:
            job-type: whale-say             
        spec:
          containers:
          - name: whale-say-container
            image: docker/whalesay
            command: ["cowsay","Hello DevNation"]
          restartPolicy: Never
EOF
----

하지만 Terminal#2의 감시 창을 보면..

* *Terminal#2에서 확인*

[.console-output]
[source,bash]
----
NAME                  READY   STATUS      RESTARTS   AGE
----

CronJob을 설정하는 동안 Pod가 실행되고 있지 않습니다(약 10초마다 한 번만 확인됩니다. 아래 경고 참조). +
cronjob이 실행되기를 기다리는 동안 *터미널 1*을 사용하여 `cronjob` 이 어떻게 실행되는지 확인할 수 있습니다. 

* *Terminal#1에서 수행*

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get cronjobs -w #<.>
----
<.> `-w` 플래그는 출력을 감시하도록 지시하지만( *Terminal#2* 에서 수행하는 것과 유사) 관찰된 리소스(이 경우 `cronjob`)의 상태가 있을 때만 다시 게시합니다. 

다음은 거의 3분 동안 기다린 후의 대표적인 출력입니다(작업이 다시 시작됨).

[.console-output]
[source,bash,subs="+macros,+attributes,+quotes"]
----
NAME                SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
whale-say-cronjob   * * * * *   False     #1#        0s              #20s# #<.>
whale-say-cronjob   * * * * *   False     0        31s             51s
whale-say-cronjob   * * * * *   False     #1#        0s              #80s# #<.>
whale-say-cronjob   * * * * *   False     0        23s             103s
whale-say-cronjob   * * * * *   False     #1#        1s              #2m21s#
----
<.> 첫 번째 호출을 시작하는 데 시간이 걸렸습니다. 이는 'cronjob' 일정의 기능이 아니었습니다.
<.> 다음 번 작업이 활성화되는 시간은 첫 번째 작업이 활성화된 후(AGE 기준) 약 60초 후에 발생한다는 점에 유의하세요.


cronjob이 ACTIVE로 이동할 때마다(위의 강조 표시 참조) *Terminal#2* 에 다음이 표시되어야 함을 알 수 있습니다.


[.console-output]
[source,bash]
----
NAME                              READY  STATUS     AGE  NODE
whale-say-cronjob-27108480-2ws6k  0/1    Completed  46s  devnation-m02
----


[WARNING]
====
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/[공식 Kubernetes 문서] 에 따르면: CronJob은 스케줄에 따라 실행 시간마다 Job 객체를 생성합니다. 하지만 "대략적으로" 생성된다고 표현하는 이유는 특정 상황에서 두 개의 Job이 생성되거나, 아무 Job도 생성되지 않을 수 있는 경우가 있기 때문입니다. 이러한 상황은 드물지만 완전히 방지할 수는 없습니다. 따라서 Job은 **멱등성(idempotent)**을 가져야 합니다.
====

`describe` 하위 명령을 사용하여 cronjob을 살펴보겠습니다. kbd:[CTRL+c]를 사용하여 `oc get cronjobs -w` 명령을 취소하고 다음으로 바꿉니다.

* *Terminal#1에서 수행*

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe cronjobs
----

그러면 다음과 같은 내용이 표시됩니다.

[.console-output]
[source,bash,subs="+quotes"]
----
Name:                          whale-say-cronjob
Namespace:                     myspace
Labels:                        <none>
Annotations:                   <none>
Schedule:                      * * * * *
Concurrency Policy:            Allow
Suspend:                       False
#Successful Job History Limit:  3# #<.>
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:  #job-type=whale-say#
  Containers:
   whale-say-container:
    Image:      docker/whalesay
    Port:       <none>
    Host Port:  <none>
    Command:
      cowsay
      Hello DevNation
    Environment:     <none>
    Mounts:          <none>
  Volumes:           <none>
#Last Schedule Time:  Sat, 17 Jul 2021 08:06:00 +0000# #<.>
Active Jobs:         whale-say-cronjob-27108486
Events:
  Type    Reason            Age    From                Message
  ----    ------            ----   ----                -------
  Normal  SuccessfulCreate  6m21s  cronjob-controller  Created job whale-say-cronjob-27108480
  Normal  SawCompletedJob   6m1s   cronjob-controller  Saw completed job: whale-say-cronjob-27108480, status: Complete
  Normal  SuccessfulCreate  5m21s  cronjob-controller  Created job whale-say-cronjob-27108481
  Normal  SawCompletedJob   4m56s  cronjob-controller  Saw completed job: whale-say-cronjob-27108481, status: Complete
  Normal  SuccessfulCreate  4m21s  cronjob-controller  Created job whale-say-cronjob-27108482
  Normal  SawCompletedJob   3m56s  cronjob-controller  Saw completed job: whale-say-cronjob-27108482, status: Complete
  Normal  SuccessfulCreate  3m21s  cronjob-controller  Created job whale-say-cronjob-27108483
  Normal  SawCompletedJob   2m48s  cronjob-controller  Saw completed job: whale-say-cronjob-27108483, status: Complete
  Normal  SuccessfulDelete  2m46s  cronjob-controller  Deleted job whale-say-cronjob-27108480
  Normal  SuccessfulCreate  2m20s  cronjob-controller  Created job whale-say-cronjob-27108484
  Normal  SawCompletedJob   104s   cronjob-controller  Saw completed job: whale-say-cronjob-27108484, status: Complete
  Normal  SuccessfulDelete  101s   cronjob-controller  Deleted job whale-say-cronjob-27108481
  Normal  SuccessfulCreate  81s    cronjob-controller  Created job whale-say-cronjob-27108485
  Normal  SawCompletedJob   54s    cronjob-controller  Saw completed job: whale-say-cronjob-27108485, status: Complete
  Normal  SuccessfulDelete  52s    cronjob-controller  Deleted job whale-say-cronjob-27108482
  Normal  SuccessfulCreate  21s    cronjob-controller  Created job whale-say-cronjob-27108486
  Normal  SawCompletedJob   1s     cronjob-controller  Saw completed job: whale-say-cronjob-27108486, status: Complete
----
<.> Kubernetes는 일정 시간이 지나면 작업을 정리합니다. 
<.> _Last Schedule Time_ 은 작업이 마지막으로 실행된 시간을 표시합니다.

일정이 활성화될 때마다 CronJob이 `Job` 을 생성(이후 Pod 생성)한다는 점에 유의하는 것이 중요합니다.


* *Terminal#1에서 수행*
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get jobs
----

cronjob이 3분 이상 지속된 후의 출력 예는 다음과 같습니다.

[.console-output]
[source,bash]
----
NAME                         COMPLETIONS   DURATION   AGE
whale-say-cronjob-27108487   1/1           19s        2m37s
whale-say-cronjob-27108488   1/1           20s        97s
whale-say-cronjob-27108489   1/1           21s        37s
----


마지막으로 모든 작업을 기록하여 작업 기록의 효과를 확인할 수 있습니다.


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc logs \
  -l job-type=whale-say \
  --tail=-1
----
NOTE: 이번에는 'job-type'(위의 사용자 정의 라벨) 라벨이 'whale'로 설정된 모든 항목에 대한 로그를 얻으려고 합니다.

.NOTE
****
덜 구체적이기는 하지만, 다음과 같이 라벨의 값과 일치하는지 확인하지 않음으로써_ 맞춤 라벨 없이 고래 작업 로그를 찾을 수_있습니다_.

[.console-input]
[source,bash,subs="+macros,+attributes,+quotes"]
----
oc logs -l job-name --tail=-1
----

이는 기본적으로 'job-name'이라는 라벨이 있는 모든 Pod와 일치해야 함을 나타냅니다.

****

[.console-output]
[source,bash]
----
 _________________ 
< Hello DevNation >
 ----------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
 _________________ 
< Hello DevNation >
 ----------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
 _________________ 
< Hello DevNation >
 ----------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
----


=== Clean Up

* *Terminal#1에서 수행*
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete cronjob whale-say-cronjob
----


