= DaemonSets
include::_attributes.adoc[]

Kubernetes에서 StatefulSet(상태 저장 세트)과 DaemonSet(데몬 세트)는 Pod 개수만 유지하는 ReplicaSet과 다르게 특정한 목적을 가진 Pod 관리 컨트롤러입니다.

StatefulSet은 주로 데이터 상태를 유지해야 하는 Pod (DB, 메시지 큐 등)를 배포할 때 사용하고, +
DaemonSet은 모든(혹은 특정) 노드에서 반드시 실행되어야 하는 Pod (로그 수집, 모니터링 등)를 배포할 때 사용합니다. 

이전 실습에서 주로 사용한 Deployment는 ReplicaSet 기반으로 Pod를 배포하는 데, 
ReplicaSet이 Pod 개수만 유지하는 단순한 컨트롤러라면 DaemonSet은 모든(혹은 특정) 노드에서 해당 Pod를 하나씩 실행하도록 보장합니다. +

클러스터에 노드가 추가되면 해당 노드에도 Pod가 자동으로 추가됩니다. 노드가 삭제되면 해당 Pod는 다른 노드로 재예약 되지 않고 삭제됩니다.
따라서 DaemonSet을 사용하면 모든 노드에 안정적으로 Pod를 배포할 수 있습니다.

* DaemonSet을 사용하는 주요 애플리케이션
** 로그 수집:	Fluentd, Logstash, Filebeat
** 모니터링 에이전트:	Prometheus Node Exporter, Datadog Agent
** 보안 및 네트워크 관리:	Cilium, Calico, Istio CNI
** 스토리지 에이전트

== DaemonSet

DaemonSet은 Kubernetes `DaemonSet` 리소스를 사용하여 생성합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f apps/kubefiles/quarkus-daemonset.yaml
cat <<EOF | oc create -f -
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: quarkus-daemonset
  labels:
    app: quarkus-daemonset
spec:
  selector:
    matchLabels:
      app: quarkus-daemonset
  template:
    metadata:
      labels:
        app: quarkus-daemonset
    spec:
      containers:
      - name: quarkus-daemonset
        image: quay.io/rhdevelopers/quarkus-demo:v1
EOF
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get pods -o wide
----

[.console-output]
[source,bash]
----
NAME                      READY   STATUS    RESTARTS   AGE   IP           NODE            NOMINATED NODE   READINESS GATES
quarkus-daemonset-jl2t5   1/1     Running   0          23s   10.244.0.2   multinode       <none>           <none>
quarkus-daemonset-r64ql   1/1     Running   0          23s   10.244.1.2   multinode-m02   <none>           <none>
----

Quarkus Pod의 인스턴스가 모든 노드에 배포됩니다.

=== Clean Up

실습을 마쳤으면 생성했던 리소스를 삭제합니다. 

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc delete daemonset quarkus-daemonset
----
